# Generated by Django 3.2.9 on 2021-11-02 11:01

import app_car.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='نام نمایندگی')),
                ('code', models.CharField(max_length=10, null=True, verbose_name='کد نمایندگی')),
                ('phone', models.CharField(max_length=11, null=True, verbose_name='شماره تماس')),
                ('status', models.CharField(choices=[('OFFICIAL', 'رسمی'), ('OTHER', 'متفرقه')], default='official', max_length=10)),
                ('address', models.TextField(null=True)),
                ('url_site', models.URLField()),
            ],
            options={
                'verbose_name': 'نام نمایندگی',
                'verbose_name_plural': 'نام نمایندگی ها',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='نام برند')),
                ('country', models.CharField(max_length=30, null=True, verbose_name='نام کشور تولید کننده')),
                ('introduction', models.TextField(blank=True, null=True, verbose_name='معرفی برند')),
            ],
            options={
                'verbose_name': 'نام برند',
                'verbose_name_plural': 'نام  برندها',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='نام خودرو')),
                ('year', models.PositiveSmallIntegerField(null=True, verbose_name='سال تولید')),
                ('price', models.PositiveBigIntegerField(null=True, verbose_name='قیمت')),
                ('stock', models.BooleanField(default=True, help_text='در صورت موجود بودن علامت کنار آن قابل مشاهده است', verbose_name='موجود')),
                ('image', models.ImageField(upload_to=app_car.utils.path_car, validators=[app_car.utils.validat_image], verbose_name='تصویر خودرو')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_car.agency', verbose_name='نام نمایندگی')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_car.company', verbose_name='نام برند')),
            ],
            options={
                'verbose_name': 'نام خودرو',
                'verbose_name_plural': 'نام خودروها',
            },
        ),
    ]
