# Generated by Django 3.2.9 on 2021-11-02 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='app_car.agency', verbose_name='نام نمایندگی'),
        ),
        migrations.AlterField(
            model_name='car',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='app_car.company', verbose_name='نام برند'),
        ),
    ]
