# Generated by Django 3.2.9 on 2021-11-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_car', '0002_auto_20211102_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, verbose_name='پیوند یکتا'),
        ),
    ]
