# Generated by Django 3.2.9 on 2021-11-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_car', '0004_car_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='descript',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
    ]
