# Generated by Django 3.2.9 on 2021-11-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_car', '0008_alter_car_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='code',
            field=models.PositiveSmallIntegerField(blank=True, null=True, unique=True, verbose_name='کد خودرو'),
        ),
    ]
